### PR TITLE
Visibility support

### PR DESCRIPTION
**Pull request by stubbers**
Most instances have pretty strict rules around needing to have bots be unlisted. This adds the ability to configure visibility on the node

Also adds some relevant files to .gitignore to allow easier git management

### CODE REVIEW

**Comment by valerio-vaccaro** [comment]
nice

**Comment by mkarliner** [comment]
+1

**Comment by hardillb** [comment]
Any chance of tagging a release and pushing it to npm (and then requesting an update on flows.nodered.org) please so this update installable.

Thanks

**Comment by valerio-vaccaro** [comment]
sorry i forgot to cut a new release! 

I create package 0.1.1, let me know if works well (flows i think will be update automagically)

**Comment by hardillb** [comment]
No, you need to request an update on flows, (but anybody can do it if signed in). I have triggered the update request.

But it can then take up to 30mins for the catalogue file to be published.

**Comment by valerio-vaccaro** [comment]
thanks!

**Pull request merged**
